// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../../../../index.js";

/**
 * @example
 *     {
 *         offerId: "offerId",
 *         body: {}
 *     }
 */
export interface AcceptOfferRequest {
    /** Offer ID */
    offerId: string;
    body: Talkif.AcceptTransferOfferRequest | null;
}
