// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         config: {
 *             "key": "value"
 *         },
 *         kind: "phone",
 *         name: "Sales desk"
 *     }
 */
export interface CreateTransferDestinationRequest {
    /**
     * Kind-specific settings. For `app`: `{ "url": "https://..." }`, the HTTPS endpoint that
     * receives signed `transfer.offer` webhooks; the signing secret is returned once, in the
     * create response. For `available_humans`: `{ "userIds": null }` (everyone
     * available) or `{ "userIds": ["<user id>", ...] }`, plus optional `"tags": ["sales", ...]`
     * to ring only members with any of those tags (team accounts); members are rung only
     * within their available hours. For `phone`: `{ "number": "+E164", "callerId": "did" | "caller",
     * "fromNumberId"?: "<id of one of your phone numbers>" }`. `fromNumberId` picks the number
     * that places the call; when omitted, the number the original call came in on is used.
     */
    config: Record<string, unknown>;
    /** Disabled destinations are skipped when a transfer rings. Default `true`. */
    enabled?: boolean | null;
    /**
     * Destination kind: `phone`, `available_humans` (the people who are
     * available for calls in the dashboard), or `app` (your own server)
     */
    kind: string;
    /** Display name, unique per account (1–100 characters). */
    name: string;
}
