// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../../../../index.js";

/**
 * @example
 *     {
 *         members: [{
 *                 destinationId: "destinationId"
 *             }],
 *         name: "Sales team"
 *     }
 */
export interface CreateDestinationGroupRequest {
    /** 1–10 destinations of this account, in ring order. */
    members: Talkif.DestinationGroupMember[];
    /** Display name, unique per account (1–100 characters). */
    name: string;
    /** `simultaneous` (default): ring every member at once, first to answer wins. */
    strategy?: string | null;
    /** Upper bound for the whole attempt, 5–60 seconds. Default 30. */
    totalTimeoutSecs?: number | null;
}
