// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         offerId: "offerId"
 *     }
 */
export interface DeclineOfferRequest {
    /** Offer ID */
    offerId: string;
}
