// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         memberId: "memberId"
 *     }
 */
export interface GetMemberHoursRequest {
    /** Membership ID */
    memberId: string;
}
