// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListGroupsRequest {
    /** Page size */
    limit?: number;
    /** Page offset */
    offset?: number;
}
