// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         memberId: "memberId",
 *         tags: ["sales", "billing"]
 *     }
 */
export interface SetMemberTagsRequest {
    /** Membership ID */
    memberId: string;
    /**
     * The member's complete tag list; it replaces the current one. Tags are
     * normalized: trimmed, lowercased, spaces become `-`. Allowed: `a`–`z`,
     * `ı ğ ü ş ö ç`, digits, `-` and `_`, at most 32 characters each, at most
     * 20 tags. An empty list removes every tag.
     */
    tags: string[];
}
