// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../../../../index.js";

/**
 * @example
 *     {
 *         memberId: "memberId",
 *         status: "available"
 *     }
 */
export interface SetMemberAvailabilityRequest {
    /** Membership ID */
    memberId: string;
    /** `available`, `away` or `offline` */
    status: Talkif.MemberAvailabilityStatus;
    /**
     * For `away`/`offline`: when it ends by itself (RFC 3339, in the future,
     * at most 30 days ahead). Omit for "until I change it". Not allowed with
     * `available`.
     */
    until?: string | null;
}
