// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../../../../index.js";

/**
 * @example
 *     {
 *         memberId: "memberId",
 *         body: {
 *             timezone: "Europe/Istanbul",
 *             weekly: {}
 *         }
 *     }
 */
export interface SetMemberHoursRequest {
    /** Membership ID */
    memberId: string;
    body: Talkif.MemberHours;
}
