// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdateDestinationGroupRequest {
    /** Destination group ID */
    id: string;
    /** Replaces the whole member list. */
    members?: Talkif.DestinationGroupMember[] | null;
    name?: string | null;
    strategy?: string | null;
    totalTimeoutSecs?: number | null;
}
