// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdateTransferDestinationRequest {
    /** Destination ID */
    id: string;
    /** Replaces the whole kind-specific settings object. */
    config?: Record<string, unknown> | null;
    enabled?: boolean | null;
    name?: string | null;
}
