// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Talkif from "../../../index.js";

export declare namespace PhoneNumbersClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Manage phone numbers for calling
 */
export class PhoneNumbersClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<PhoneNumbersClient.Options>;

    constructor(options: PhoneNumbersClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * GET /api/v1/phone/numbers
     *
     * @param {Talkif.ListPhoneNumbersRequest} request
     * @param {PhoneNumbersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.phoneNumbers.listPhoneNumbers()
     */
    public listPhoneNumbers(
        request: Talkif.ListPhoneNumbersRequest = {},
        requestOptions?: PhoneNumbersClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.PhoneNumberListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listPhoneNumbers(request, requestOptions));
    }

    private async __listPhoneNumbers(
        request: Talkif.ListPhoneNumbersRequest = {},
        requestOptions?: PhoneNumbersClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.PhoneNumberListResponse>> {
        const { limit, offset } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            offset,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                "api/v1/phone/numbers",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.PhoneNumberListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/phone/numbers");
    }

    /**
     * GET /api/v1/phone/numbers/twilio/available
     *
     * Query Parameters:
     * - `providerId` (required): Provider ID
     * - `countryCode` (required): ISO country code (e.g., "US", "GB")
     * - `numberType` (optional): "local", "toll_free", or "mobile" (default: "local")
     * - `areaCode` (optional): Area code filter (US/Canada only)
     * - `contains` (optional): Pattern to match (supports wildcards: *, %)
     * - `inPostalCode` (optional): Filter by postal/ZIP code
     * - `inRegion` (optional): Filter by state/region
     * - `inRateCenter` (optional): Filter by rate center
     * - `inLata` (optional): Filter by LATA
     * - `inLocality` (optional): Filter by city
     * - `nearNumber` (optional): Find numbers near this phone number
     * - `nearLatLong` (optional): Find numbers near lat,long
     * - `distance` (optional): Radius in miles (default: 25, max: 500)
     * - `smsEnabled` (optional): Filter SMS-capable numbers
     * - `mmsEnabled` (optional): Filter MMS-capable numbers
     * - `voiceEnabled` (optional): Filter voice-capable numbers
     * - `faxEnabled` (optional): Filter fax-capable numbers
     * - `beta` (optional): Filter beta numbers
     * - `excludeAllAddressRequired` (optional): Exclude numbers requiring any address
     * - `excludeLocalAddressRequired` (optional): Exclude numbers requiring local address
     * - `excludeForeignAddressRequired` (optional): Exclude numbers requiring foreign address
     * - `limit` (optional): Max results (default: 20, max: 1000)
     *
     * @param {Talkif.ListAvailableNumbersRequest} request
     * @param {PhoneNumbersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.phoneNumbers.listAvailableNumbers({
     *         providerId: "providerId",
     *         countryCode: "countryCode"
     *     })
     */
    public listAvailableNumbers(
        request: Talkif.ListAvailableNumbersRequest,
        requestOptions?: PhoneNumbersClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.AvailableNumbersResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listAvailableNumbers(request, requestOptions));
    }

    private async __listAvailableNumbers(
        request: Talkif.ListAvailableNumbersRequest,
        requestOptions?: PhoneNumbersClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.AvailableNumbersResponse>> {
        const {
            providerId,
            countryCode,
            numberType,
            areaCode,
            contains,
            inPostalCode,
            inRegion,
            inRateCenter,
            inLata,
            inLocality,
            nearNumber,
            nearLatLong,
            distance,
            smsEnabled,
            mmsEnabled,
            voiceEnabled,
            faxEnabled,
            beta,
            excludeAllAddressRequired,
            excludeLocalAddressRequired,
            excludeForeignAddressRequired,
            limit,
        } = request;
        const _queryParams: Record<string, unknown> = {
            providerId,
            countryCode,
            numberType,
            areaCode,
            contains,
            inPostalCode,
            inRegion,
            inRateCenter,
            inLata,
            inLocality,
            nearNumber,
            nearLatLong,
            distance,
            smsEnabled,
            mmsEnabled,
            voiceEnabled,
            faxEnabled,
            beta,
            excludeAllAddressRequired,
            excludeLocalAddressRequired,
            excludeForeignAddressRequired,
            limit,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                "api/v1/phone/numbers/twilio/available",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.AvailableNumbersResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/phone/numbers/twilio/available",
        );
    }

    /**
     * GET /api/v1/phone/numbers/twilio/available-countries
     *
     * @param {Talkif.ListAvailableCountriesRequest} request
     * @param {PhoneNumbersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.phoneNumbers.listAvailableCountries({
     *         providerId: "providerId"
     *     })
     */
    public listAvailableCountries(
        request: Talkif.ListAvailableCountriesRequest,
        requestOptions?: PhoneNumbersClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__listAvailableCountries(request, requestOptions));
    }

    private async __listAvailableCountries(
        request: Talkif.ListAvailableCountriesRequest,
        requestOptions?: PhoneNumbersClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { providerId } = request;
        const _queryParams: Record<string, unknown> = {
            providerId,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                "api/v1/phone/numbers/twilio/available-countries",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/phone/numbers/twilio/available-countries",
        );
    }

    /**
     * GET /api/v1/phone/numbers/twilio/pricing
     *
     * @param {Talkif.GetPricingRequest} request
     * @param {PhoneNumbersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.phoneNumbers.getPricing({
     *         providerId: "providerId",
     *         countryCode: "countryCode"
     *     })
     */
    public getPricing(
        request: Talkif.GetPricingRequest,
        requestOptions?: PhoneNumbersClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.PhoneNumberPricing> {
        return core.HttpResponsePromise.fromPromise(this.__getPricing(request, requestOptions));
    }

    private async __getPricing(
        request: Talkif.GetPricingRequest,
        requestOptions?: PhoneNumbersClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.PhoneNumberPricing>> {
        const { providerId, countryCode } = request;
        const _queryParams: Record<string, unknown> = {
            providerId,
            countryCode,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                "api/v1/phone/numbers/twilio/pricing",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.PhoneNumberPricing, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/phone/numbers/twilio/pricing",
        );
    }

    /**
     * POST /api/v1/phone/numbers/twilio/purchase
     *
     * @param {Talkif.PurchasePhoneNumberRequest} request
     * @param {PhoneNumbersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.BadRequestError}
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.PaymentRequiredError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.ConflictError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.phoneNumbers.purchasePhoneNumber({
     *         phoneNumber: "+15551234567",
     *         providerId: "550e8400-e29b-41d4-a716-446655440000"
     *     })
     */
    public purchasePhoneNumber(
        request: Talkif.PurchasePhoneNumberRequest,
        requestOptions?: PhoneNumbersClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.PhoneNumberResponse> {
        return core.HttpResponsePromise.fromPromise(this.__purchasePhoneNumber(request, requestOptions));
    }

    private async __purchasePhoneNumber(
        request: Talkif.PurchasePhoneNumberRequest,
        requestOptions?: PhoneNumbersClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.PhoneNumberResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                "api/v1/phone/numbers/twilio/purchase",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.PhoneNumberResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Talkif.BadRequestError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new Talkif.PaymentRequiredError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Talkif.ConflictError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/phone/numbers/twilio/purchase",
        );
    }

    /**
     * GET /api/v1/phone/numbers/:id
     *
     * @param {Talkif.GetPhoneNumberRequest} request
     * @param {PhoneNumbersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.phoneNumbers.getPhoneNumber({
     *         id: "id"
     *     })
     */
    public getPhoneNumber(
        request: Talkif.GetPhoneNumberRequest,
        requestOptions?: PhoneNumbersClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.PhoneNumberResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getPhoneNumber(request, requestOptions));
    }

    private async __getPhoneNumber(
        request: Talkif.GetPhoneNumberRequest,
        requestOptions?: PhoneNumbersClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.PhoneNumberResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/phone/numbers/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.PhoneNumberResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/phone/numbers/{id}");
    }

    /**
     * PUT /api/v1/phone/numbers/:id
     *
     * @param {Talkif.UpdatePhoneNumberRequest} request
     * @param {PhoneNumbersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.phoneNumbers.updatePhoneNumber({
     *         id: "id"
     *     })
     */
    public updatePhoneNumber(
        request: Talkif.UpdatePhoneNumberRequest,
        requestOptions?: PhoneNumbersClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.PhoneNumberResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updatePhoneNumber(request, requestOptions));
    }

    private async __updatePhoneNumber(
        request: Talkif.UpdatePhoneNumberRequest,
        requestOptions?: PhoneNumbersClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.PhoneNumberResponse>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/phone/numbers/${core.url.encodePathParam(id)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.PhoneNumberResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/api/v1/phone/numbers/{id}");
    }

    /**
     * DELETE /api/v1/phone/numbers/:id
     *
     * @param {Talkif.ReleasePhoneNumberRequest} request
     * @param {PhoneNumbersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.phoneNumbers.releasePhoneNumber({
     *         id: "id"
     *     })
     */
    public releasePhoneNumber(
        request: Talkif.ReleasePhoneNumberRequest,
        requestOptions?: PhoneNumbersClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__releasePhoneNumber(request, requestOptions));
    }

    private async __releasePhoneNumber(
        request: Talkif.ReleasePhoneNumberRequest,
        requestOptions?: PhoneNumbersClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/phone/numbers/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/api/v1/phone/numbers/{id}");
    }

    /**
     * PATCH /api/v1/phone/numbers/:phoneNumberId/connect-flow
     *
     * @param {Talkif.ConnectFlowRequest} request
     * @param {PhoneNumbersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.phoneNumbers.connectFlow({
     *         phoneNumberId: "phoneNumberId",
     *         flowId: "550e8400-e29b-41d4-a716-446655440000"
     *     })
     */
    public connectFlow(
        request: Talkif.ConnectFlowRequest,
        requestOptions?: PhoneNumbersClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.PhoneNumberResponse> {
        return core.HttpResponsePromise.fromPromise(this.__connectFlow(request, requestOptions));
    }

    private async __connectFlow(
        request: Talkif.ConnectFlowRequest,
        requestOptions?: PhoneNumbersClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.PhoneNumberResponse>> {
        const { phoneNumberId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/phone/numbers/${core.url.encodePathParam(phoneNumberId)}/connect-flow`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.PhoneNumberResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/api/v1/phone/numbers/{phoneNumberId}/connect-flow",
        );
    }

    /**
     * PATCH /api/v1/phone/numbers/:phoneNumberId/disconnect-flow
     *
     * @param {Talkif.DisconnectFlowRequest} request
     * @param {PhoneNumbersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Talkif.UnauthorizedError}
     * @throws {@link Talkif.ForbiddenError}
     * @throws {@link Talkif.NotFoundError}
     * @throws {@link Talkif.TooManyRequestsError}
     * @throws {@link Talkif.InternalServerError}
     * @throws {@link errors.TalkifError}
     * @throws {@link errors.TalkifTimeoutError}
     *
     * @example
     *     await client.phoneNumbers.disconnectFlow({
     *         phoneNumberId: "phoneNumberId"
     *     })
     */
    public disconnectFlow(
        request: Talkif.DisconnectFlowRequest,
        requestOptions?: PhoneNumbersClient.RequestOptions,
    ): core.HttpResponsePromise<Talkif.PhoneNumberResponse> {
        return core.HttpResponsePromise.fromPromise(this.__disconnectFlow(request, requestOptions));
    }

    private async __disconnectFlow(
        request: Talkif.DisconnectFlowRequest,
        requestOptions?: PhoneNumbersClient.RequestOptions,
    ): Promise<core.WithRawResponse<Talkif.PhoneNumberResponse>> {
        const { phoneNumberId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TalkifEnvironment.Production,
                `api/v1/phone/numbers/${core.url.encodePathParam(phoneNumberId)}/disconnect-flow`,
            ),
            method: "PATCH",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Talkif.PhoneNumberResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Talkif.UnauthorizedError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Talkif.ForbiddenError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Talkif.NotFoundError(_response.error.body as Talkif.ErrorResponse, _response.rawResponse);
                case 429:
                    throw new Talkif.TooManyRequestsError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Talkif.InternalServerError(
                        _response.error.body as Talkif.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TalkifError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/api/v1/phone/numbers/{phoneNumberId}/disconnect-flow",
        );
    }
}
