// This file was auto-generated by Fern from our API Definition.

/**
 * Optional accept body: a WebRTC SDP offer switches the join to WebRTC.
 */
export interface AcceptTransferOfferRequest {
    /** Identifier of the accepting client (at most 64 characters) */
    clientId?: (string | null) | undefined;
    /** WebRTC SDP offer; present = join over WebRTC, absent = WebSocket join */
    sdpOffer?: (string | null) | undefined;
}
