// This file was auto-generated by Fern from our API Definition.

/**
 * A role level inside an account or organization. Ordered: an owner passes
 * every admin check, an admin every member check, a member every agent
 * check.
 */
export const AccountRole = {
    Agent: "agent",
    Member: "member",
    Admin: "admin",
    Owner: "owner",
} as const;
export type AccountRole = (typeof AccountRole)[keyof typeof AccountRole];
