// This file was auto-generated by Fern from our API Definition.

/** Where a flow's conversation runs (spike, staging). Default `cloud`. */
export const AgentRuntime = {
    Cloud: "cloud",
    Device: "device",
} as const;
export type AgentRuntime = (typeof AgentRuntime)[keyof typeof AgentRuntime];
