// This file was auto-generated by Fern from our API Definition.

/**
 * Configuration of a "Your app" destination: the HTTPS endpoint of your
 * server that receives transfer offers.
 */
export interface AppDestinationConfig {
    /** HTTPS URL that receives signed `transfer.offer` webhooks */
    url: string;
}
