// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Available numbers matching a search
 */
export interface AvailableNumbersResponse {
    /** Numbers available for purchase */
    numbers: Talkif.AvailablePhoneNumber[];
    /** The search criteria that produced this result */
    query: Talkif.AvailableNumbersEcho;
}
