// This file was auto-generated by Fern from our API Definition.

/**
 * Search criteria echoed back with the results
 */
export interface AvailableNumbersEcho {
    /** Area code filter that was applied, if any */
    areaCode?: (string | null) | undefined;
    /** Pattern filter that was applied, if any */
    contains?: (string | null) | undefined;
    /** ISO country code that was searched */
    countryCode: string;
}
