// This file was auto-generated by Fern from our API Definition.

/**
 * Sortable fields for call history
 *
 * Values match what the dashboard's call-history table emits
 */
export const CallSortField = {
    Status: "status",
    Direction: "direction",
    Duration: "duration",
    TotalCost: "totalCost",
    StartedAt: "startedAt",
} as const;
export type CallSortField = (typeof CallSortField)[keyof typeof CallSortField];
