// This file was auto-generated by Fern from our API Definition.

/** Caller ID presented to a phone destination. */
export const CallerIdPolicy = {
    Did: "did",
    Caller: "caller",
} as const;
export type CallerIdPolicy = (typeof CallerIdPolicy)[keyof typeof CallerIdPolicy];
