// This file was auto-generated by Fern from our API Definition.

/**
 * One member of a destination group.
 */
export interface DestinationGroupMember {
    /** A destination of the same account. */
    destinationId: string;
    /** How long this member rings, 5–45 seconds. */
    ringTimeoutSecs?: number | undefined;
}
