// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * A destination group: a named set of destinations that ring together as one
 * transfer target.
 */
export interface DestinationGroup {
    createdAt: string;
    id: string;
    members: Talkif.DestinationGroupMember[];
    name: string;
    strategy: string;
    totalTimeoutSecs: number;
    updatedAt: string;
}
