// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Page of destination groups
 */
export interface DestinationGroupListResponse {
    /** Items on this page */
    groups: Talkif.DestinationGroup[];
    /** Pagination metadata */
    meta: Talkif.PaginationMeta;
}
