// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * LLM model with pricing information
 */
export interface LlmModel {
    /** Model capabilities */
    capabilities: Talkif.LlmCapabilities;
    /** Context window size (tokens) */
    contextWindow?: (number | null) | undefined;
    deprecation?: (Talkif.ModelDeprecation | null) | undefined;
    /** Model description */
    description?: (string | null) | undefined;
    /** Model identifier (e.g., "gpt-4o", "claude-3-5-sonnet") */
    modelId: string;
    /** Display name (e.g., "GPT-4o", "Claude 3.5 Sonnet") */
    name: string;
    pricing?: (Talkif.LlmPricing | null) | undefined;
}
