// This file was auto-generated by Fern from our API Definition.

/** Whether a member takes transferred calls: `available`, `away` or `offline`. */
export const MemberAvailabilityStatus = {
    Available: "available",
    Away: "away",
    Offline: "offline",
} as const;
export type MemberAvailabilityStatus = (typeof MemberAvailabilityStatus)[keyof typeof MemberAvailabilityStatus];
