// This file was auto-generated by Fern from our API Definition.

/**
 * Role of a member in your organization: `owner`, `admin`, `member` or
 * `agent`.
 */
export const MemberRole = {
    Owner: "owner",
    Admin: "admin",
    Member: "member",
    Agent: "agent",
} as const;
export type MemberRole = (typeof MemberRole)[keyof typeof MemberRole];
