// This file was auto-generated by Fern from our API Definition.

/**
 * A range of local time on one day. It never crosses midnight: for an
 * overnight shift use two ranges on two days, e.g. `22:00`–`24:00` and
 * `00:00`–`06:00`.
 */
export interface MemberHoursRange {
    /** End, `HH:MM` (00:01–24:00), exclusive; after `start` on the same day */
    end: string;
    /** Start, `HH:MM` (00:00–23:59), inclusive */
    start: string;
}
