// This file was auto-generated by Fern from our API Definition.

/**
 * One tag in use in your organization.
 */
export interface MemberTagUsage {
    /** How many members carry the tag */
    memberCount: number;
    /** The tag, normalized */
    tag: string;
}
