// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * A member's availability.
 */
export interface MemberAvailability {
    /** On a transferred call right now; not offered another one */
    busy: boolean;
    /** Membership ID */
    memberId: string;
    /** Why the platform set it (`missed_calls`), with `source: auto` */
    reason?: (string | null) | undefined;
    source?: (Talkif.MemberAvailabilitySource | null) | undefined;
    /**
     * The status in force now (an away/offline whose end time passed reads
     * as `available`)
     */
    status: Talkif.MemberAvailabilityStatus;
    /** When `away`/`offline` ends by itself; `null` = until changed */
    until?: (string | null) | undefined;
    /** When the current `away`/`offline` was set */
    updatedAt?: (string | null) | undefined;
    /** User ID */
    userId: string;
}
