// This file was auto-generated by Fern from our API Definition.

/**
 * A member's tags.
 */
export interface MemberTagsResponse {
    /** Membership ID of the member in your organization */
    memberId: string;
    /** The member's tags, normalized and sorted */
    tags: string[];
    /** User ID of the member (the ID `available_humans` destinations list in `userIds`) */
    userId: string;
}
