// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Tags in use in your organization.
 */
export interface MemberTagCatalogResponse {
    /** Every tag at least one member carries, sorted */
    tags: Talkif.MemberTagUsage[];
}
