// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Ranges per weekday, at most 6 per day, not overlapping. A missing or
 * empty day has no hours.
 */
export interface MemberWeeklyHours {
    /** Ranges on Friday */
    fri?: Talkif.MemberHoursRange[] | undefined;
    /** Ranges on Monday */
    mon?: Talkif.MemberHoursRange[] | undefined;
    /** Ranges on Saturday */
    sat?: Talkif.MemberHoursRange[] | undefined;
    /** Ranges on Sunday */
    sun?: Talkif.MemberHoursRange[] | undefined;
    /** Ranges on Thursday */
    thu?: Talkif.MemberHoursRange[] | undefined;
    /** Ranges on Tuesday */
    tue?: Talkif.MemberHoursRange[] | undefined;
    /** Ranges on Wednesday */
    wed?: Talkif.MemberHoursRange[] | undefined;
}
