// This file was auto-generated by Fern from our API Definition.

/**
 * Status of a member in your organization: `active`, `pending` (invited,
 * not yet joined) or `suspended`.
 */
export const MemberStatus = {
    Active: "active",
    Pending: "pending",
    Suspended: "suspended",
} as const;
export type MemberStatus = (typeof MemberStatus)[keyof typeof MemberStatus];
