// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * A member's weekly available hours. A transfer to people rings the member
 * only inside these hours, evaluated on the local clock of `timezone` (a
 * 09:00–18:00 range stays 09:00–18:00 across daylight-saving changes).
 */
export interface MemberHours {
    /** IANA timezone the times are in */
    timezone: string;
    /** Ranges per weekday (`mon` … `sun`) */
    weekly: Talkif.MemberWeeklyHours;
}
