// This file was auto-generated by Fern from our API Definition.

/**
 * Who set the status: the `member`, an owner/`admin`, or the platform
 * (`auto`, after missed calls).
 */
export const MemberAvailabilitySource = {
    Member: "member",
    Admin: "admin",
    Auto: "auto",
} as const;
export type MemberAvailabilitySource = (typeof MemberAvailabilitySource)[keyof typeof MemberAvailabilitySource];
