// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * A member's available hours.
 */
export interface MemberHoursResponse {
    hours?: (Talkif.MemberHours | null) | undefined;
    /** Membership ID of the member in your organization */
    memberId: string;
    /** User ID of the member */
    userId: string;
}
