// This file was auto-generated by Fern from our API Definition.

/**
 * Scheduled retirement of a model. Until `retiresOn` the model works as
 * usual; from that day calls that name it run on `replacedBy` instead, so
 * published agents keep working without changes.
 */
export interface ModelDeprecation {
    /** Model from the same provider that runs instead. */
    replacedBy: string;
    /** First day the model no longer runs (UTC date). */
    retiresOn: string;
}
