// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * What the caller may do in the selected account.
 */
export interface PermissionsResponse {
    /** The selected account */
    accountId: string;
    /** Permissions you hold, as `resource:read` / `resource:write` */
    permissions: string[];
    /** Your role in it: `owner`, `admin`, `member` or `agent` */
    role: Talkif.AccountRole;
}
