// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Configuration of a phone destination.
 */
export interface PhoneDestinationConfig {
    /** Caller ID shown to the person answering. */
    callerId?: Talkif.CallerIdPolicy | undefined;
    /**
     * Which of the account's phone numbers places the call (its provider
     * decides the route). Omitted: the number the original call came in on.
     */
    fromNumberId?: (string | null) | undefined;
    /** Number to ring, E.164. */
    number: string;
}
