// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * One built-in role and what it may do.
 */
export interface RoleDefinition {
    /** Permissions the role holds, as `resource:read` / `resource:write` */
    permissions: string[];
    /** `owner`, `admin`, `member` or `agent` */
    role: Talkif.AccountRole;
}
