// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * The built-in roles, highest first.
 */
export interface RolesResponse {
    roles: Talkif.RoleDefinition[];
}
