// This file was auto-generated by Fern from our API Definition.

/** Sort direction for list queries */
export const SortDirection = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type SortDirection = (typeof SortDirection)[keyof typeof SortDirection];
