// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * STT model with pricing information
 */
export interface SttModel {
    /** Model capabilities */
    capabilities: Talkif.SttCapabilities;
    deprecation?: (Talkif.ModelDeprecation | null) | undefined;
    /** Model description */
    description?: (string | null) | undefined;
    /** Supported languages */
    languages: Talkif.LanguageInfo[];
    /** Model identifier (e.g., "nova-2") */
    modelId: string;
    /** Display name (e.g., "Nova 2") */
    name: string;
    pricing?: (Talkif.SttPricing | null) | undefined;
}
