// This file was auto-generated by Fern from our API Definition.

/**
 * Who is calling.
 */
export interface TransferOfferCaller {
    /** Contact name, when the caller is a known contact */
    name?: (string | null) | undefined;
    /** Caller's number in E.164 format; null when the call has none (web calls) */
    number?: (string | null) | undefined;
}
