// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Page of transfer destinations
 */
export interface TransferDestinationListResponse {
    /** Items on this page */
    destinations: Talkif.TransferDestination[];
    /** Pagination metadata */
    meta: Talkif.PaginationMeta;
}
