// This file was auto-generated by Fern from our API Definition.

/**
 * WebSocket join: a single-use URL for the call's audio.
 */
export interface TransferOfferJoin {
    /** Call joined */
    callId: string;
    /** The join token must be used before this time */
    expiresAt: string;
    /** The single-use join token (already in `joinUrl`) */
    joinToken: string;
    /** WebSocket URL to join the call; carries the single-use join token */
    joinUrl: string;
}
