// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * A member of your organization, with the tags and available hours that
 * decide which transfers ring them.
 */
export interface TransferMember {
    /**
     * Whether the member takes calls now (their own choice or an admin's;
     * an away/offline whose end time passed reads as `available`)
     */
    availability: Talkif.MemberAvailabilityStatus;
    /** On a transferred call right now; not offered another one */
    busy: boolean;
    hours?: (Talkif.MemberHours | null) | undefined;
    /** Membership ID; use it in the member's `tags` and `hours` paths */
    memberId: string;
    /** Full name */
    name: string;
    /** Role in the organization */
    role: Talkif.MemberRole;
    /** Membership status */
    status: Talkif.MemberStatus;
    /** The member's tags, normalized and sorted */
    tags: string[];
    /** User ID; the ID `available_humans` destinations list in `userIds` */
    userId: string;
}
