// This file was auto-generated by Fern from our API Definition.

/**
 * One logged delivery to an app destination.
 */
export interface TransferAppDelivery {
    /** Call transferred (null for test sends) */
    callId?: (string | null) | undefined;
    /** When the delivery was sent */
    createdAt: string;
    /** The delivery's `deliveryId` (null for deliveries logged before it existed) */
    deliveryId?: (string | null) | undefined;
    /** Time until the response, in milliseconds */
    durationMs: number;
    /** Why the delivery did not ring (see `TransferAppDeliveryResult.error`) */
    error?: (string | null) | undefined;
    /** Unique identifier of the delivery */
    id: string;
    /**
     * `test` (a test send), `offer` (a real transfer offer) or `withdrawn` (the
     * notice that an offer stopped ringing)
     */
    kind: string;
    /** Offer delivered (null for test sends) */
    offerId?: (string | null) | undefined;
    /** HTTP status your server answered with */
    statusCode?: (number | null) | undefined;
}
