// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * WebRTC join: the SDP answer plus the ICE servers to keep using
 * (short-lived TURN credentials).
 */
export interface TransferOfferWebRtcAnswer {
    /** Call joined */
    callId: string;
    /** The TURN credentials stop working after this time */
    expiresAt: string;
    /** ICE servers for the connection */
    iceServers: Talkif.IceServerEntry[];
    /** SDP answer to apply to your peer connection */
    sdpAnswer: string;
}
