// This file was auto-generated by Fern from our API Definition.

/**
 * Outcome of one webhook delivery.
 */
export interface TransferAppDeliveryResult {
    /** Unique id of the delivery (`deliveryId` in the body, `Talkif-Delivery-Id` header) */
    deliveryId: string;
    /** Time until the response, in milliseconds */
    durationMs: number;
    /**
     * Why the delivery did not ring: `No response within 3 s`, `Could not
     * connect`, `Blocked address`, `TLS error`, `HTTP <status>` or `Delivery is
     * unavailable`; null after a 2xx answer
     */
    error?: (string | null) | undefined;
    /** HTTP status your server answered with (null when no response arrived) */
    statusCode?: (number | null) | undefined;
}
