// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * Every member of your organization with their tags and hours.
 */
export interface TransferMemberListResponse {
    /** Members of the organization */
    members: Talkif.TransferMember[];
}
