// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * The accept reply: the WebSocket shape (no body) or the WebRTC shape
 * (`sdpOffer` in the body).
 */
export type TransferOfferAcceptResponse =
    /**
     * WebSocket join (accept without a body) */
    | Talkif.TransferOfferJoin
    /**
     * WebRTC join (accept with `sdpOffer`) */
    | Talkif.TransferOfferWebRtcAnswer;
