// This file was auto-generated by Fern from our API Definition.

/** Transcript speaker type identifying who spoke a message */
export const TranscriptSpeaker = {
    Ai: "ai",
    Human: "human",
    Colleague: "colleague",
} as const;
export type TranscriptSpeaker = (typeof TranscriptSpeaker)[keyof typeof TranscriptSpeaker];
