// This file was auto-generated by Fern from our API Definition.

/**
 * Body of the `transfer.offer.withdrawn` webhook: the offer stopped ringing
 * without your app taking it. Sent once, best effort, without retries.
 */
export interface TransferOfferWithdrawn {
    /** Call it belonged to */
    callId: string;
    /** Unique id of this webhook delivery (also the `Talkif-Delivery-Id` header) */
    deliveryId: string;
    /** Offer that stopped ringing */
    offerId: string;
    /**
     * `answered_elsewhere` (another destination took the call), `cancelled`
     * (the caller hung up or the transfer was called off) or `expired`
     */
    reason: string;
    /** Event type, always `transfer.offer.withdrawn` */
    type: string;
}
