// This file was auto-generated by Fern from our API Definition.

/**
 * A transfer destination: somewhere a flow's Transfer node can send a call.
 */
export interface TransferDestination {
    config: Record<string, unknown>;
    createdAt: string;
    enabled: boolean;
    id: string;
    /**
     * Destination kind: `phone`, `available_humans` (the people who are
     * available for calls in the dashboard), or `app` (your own server)
     */
    kind: string;
    name: string;
    /**
     * App destinations, after a rotation: until this time webhooks are also signed
     * with the previous secret (a second `v1=` in `Talkif-Signature`)
     */
    previousSecretExpiresAt?: (string | null) | undefined;
    /**
     * App destinations: the secret that signs the webhooks. Returned only when the
     * destination is created or its secret rotated; store it, it is not shown again
     */
    signingSecret?: (string | null) | undefined;
    /** App destinations: the last characters of the signing secret, to tell secrets apart */
    signingSecretHint?: (string | null) | undefined;
    updatedAt: string;
}
