// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * The latest deliveries to an app destination, newest first.
 */
export interface TransferAppDeliveryListResponse {
    /** Up to 20 deliveries, newest first */
    deliveries: Talkif.TransferAppDelivery[];
}
