// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * A transfer offer to your app: the body of the `transfer.offer` webhook and
 * of `GET /api/v1/transfers/offers/{offerId}`.
 */
export interface TransferOffer {
    /**
     * Accept before this time (it can be earlier than `expiresAt`: joining the
     * call takes a few seconds)
     */
    acceptUntil: string;
    /** Call being transferred */
    callId: string;
    caller: Talkif.TransferOfferCaller;
    case?: (Talkif.TransferOfferCase | null) | undefined;
    /**
     * Unique id of this webhook delivery, also sent in the `Talkif-Delivery-Id`
     * header (webhook only; absent from `GET /api/v1/transfers/offers/{offerId}`)
     */
    deliveryId?: (string | null) | undefined;
    /** The offer stops ringing at this time */
    expiresAt: string;
    /** Name of the flow that handled the call */
    flowName: string;
    /** `cold` (the caller is connected at once) or `warm` (the agent briefs you first) */
    mode: string;
    /** Offer to accept or decline */
    offerId: string;
    /** `true` for test deliveries, which cannot be accepted */
    test: boolean;
    /** Event type, always `transfer.offer` */
    type: string;
}
