// This file was auto-generated by Fern from our API Definition.

/**
 * The handoff case the agent collected before transferring.
 */
export interface TransferOfferCase {
    /** Custom fields configured on the Transfer node, and the team rung */
    fields: Record<string, string>;
    /** Why the caller is being transferred */
    reason?: (string | null) | undefined;
    /** Short summary of the conversation so far */
    summary?: (string | null) | undefined;
}
