// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../index.js";

/**
 * TTS model with pricing information
 */
export interface TtsModel {
    /** Model capabilities */
    capabilities: Talkif.TtsCapabilities;
    deprecation?: (Talkif.ModelDeprecation | null) | undefined;
    /** Model description */
    description?: (string | null) | undefined;
    /** Supported languages */
    languages: Talkif.LanguageInfo[];
    /** Model identifier (e.g., "eleven_turbo_v2_5") */
    modelId: string;
    /** Display name (e.g., "Turbo v2.5") */
    name: string;
    pricing?: (Talkif.TtsPricing | null) | undefined;
}
