// This file was auto-generated by Fern from our API Definition.

import type * as Talkif from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListCallsRequest {
    /** Maximum number of items to return (default: 20, max: 100) */
    limit?: number;
    /** Number of items to skip for pagination (default: 0) */
    offset?: number;
    /** Only include calls after this timestamp (inclusive) */
    startDate?: string;
    /** Only include calls before this timestamp (inclusive) */
    endDate?: string;
    /** Filter by call status */
    status?: Talkif.CallStatus;
    /** Filter by call direction */
    direction?: Talkif.CallDirection;
    /** Filter by call source (direct, scheduled, campaign) */
    source?: Talkif.CallSource;
    /** Filter by phone number — matches either the from or to number (E.164) */
    phoneNumber?: string;
    /** Filter by whether the call was triggered by a Meta lead form (true = lead-driven only) */
    isLead?: boolean;
    /** Filter by flow ID */
    flowId?: string;
    /** Filter by contact ID */
    contactId?: string;
    /** Filter by schedule ID (for scheduled calls) */
    scheduleId?: string;
    /** Filter by campaign ID (for campaign calls) */
    campaignId?: string;
    /** Filter by telephony provider type (channel) */
    providerType?: Talkif.CallProviderType;
    /**
     * Free-text search across the contact name and the raw from/to phone
     * numbers (case-insensitive substring). Matches calls to/from numbers that
     * were never saved as contacts.
     */
    search?: string;
    /** Field to sort results by (default: creation time) */
    sortBy?: Talkif.CallSortField;
    /** Sort direction for `sortBy` (default: desc) */
    sortDirection?: Talkif.SortDirection;
}
