// This file was auto-generated by Fern from our API Definition.

import * as Talkif from "../../src/api/index";
import { TalkifClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AiModelsClient", () => {
    test("list_providers_public", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            llm: [
                {
                    displayName: "OpenAI",
                    models: [
                        {
                            capabilities: {
                                functionCalling: true,
                                hasPriorityTier: false,
                                jsonMode: true,
                                reasoning: true,
                                reasoningEffort: ["low", "medium", "high", "xhigh", "max"],
                                streaming: true,
                                temperature: true,
                                vision: true,
                            },
                            contextWindow: 128000,
                            deprecation: { replacedBy: "eleven_v4_turbo", retiresOn: "2026-10-13" },
                            description: "Multimodal model with strong reasoning and fast inference",
                            modelId: "gpt-4o",
                            name: "GPT-4o",
                            pricing: {
                                inputPer1mTokensDisplay: "$2.50",
                                inputPer1mTokensMicrocents: 2500000,
                                outputPer1mTokensDisplay: "$10.00",
                                outputPer1mTokensMicrocents: 10000000,
                            },
                        },
                    ],
                    provider: "openai",
                },
            ],
            stt: [
                {
                    displayName: "Deepgram",
                    models: [
                        {
                            capabilities: {
                                diarization: true,
                                multilingual: false,
                                noiseHandling: true,
                                streaming: true,
                                telephony: true,
                            },
                            deprecation: { replacedBy: "eleven_v4_turbo", retiresOn: "2026-10-13" },
                            description: "High-accuracy speech recognition optimized for telephony",
                            languages: [{ code: "en", name: "English", nativeName: "English" }],
                            modelId: "nova-2",
                            name: "Nova 2",
                            pricing: { ratePerMinuteDisplay: "$0.0077", ratePerMinuteMicrocents: 7700 },
                        },
                    ],
                    provider: "deepgram",
                },
            ],
            tts: [
                {
                    displayName: "ElevenLabs",
                    models: [
                        {
                            capabilities: {
                                emotion: false,
                                emotionOptions: [{ label: "Happiness", value: "happiness" }],
                                generationConfigSchema: {
                                    speed: { default: 1, max: 2, min: 0.5, step: 0.1 },
                                    volume: { default: 1, max: 2, min: 0.5, step: 0.1 },
                                },
                                speakerBoost: true,
                                speedControl: false,
                                streaming: true,
                                style: true,
                                voiceConversion: false,
                                volumeControl: false,
                            },
                            deprecation: { replacedBy: "eleven_v4_turbo", retiresOn: "2026-10-13" },
                            description: "High-quality multilingual text-to-speech model",
                            languages: [{ code: "en", name: "English", nativeName: "English" }],
                            modelId: "eleven_multilingual_v2",
                            name: "Multilingual v2",
                            pricing: { ratePer1kCharsDisplay: "$0.1000", ratePer1kCharsMicrocents: 100000 },
                        },
                    ],
                    provider: "elevenlabs",
                },
            ],
        };

        server.mockEndpoint().get("/api/v1/models").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.aiModels.listProvidersPublic();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_tts_voices (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            hasMore: true,
            nextPageToken: "eyJsYXN0X2lkIjoiMjFtMDAifQ",
            totalCount: 50,
            voices: [
                {
                    category: "premade",
                    description: "A calm and expressive American female voice",
                    isLegacy: false,
                    labels: { key: "value" },
                    name: "Rachel",
                    previewUrl:
                        "https://storage.googleapis.com/eleven-public-prod/premade/voices/21m00Tcm4TlvDq8ikWAM/preview.mp3",
                    publicOwnerId: "publicOwnerId",
                    recommendedModelIds: ["eleven_multilingual_v2", "eleven_turbo_v2_5"],
                    voiceId: "21m00Tcm4TlvDq8ikWAM",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/api/v1/models/tts/voices")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.aiModels.listTtsVoices();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_tts_voices (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/models/tts/voices")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.aiModels.listTtsVoices();
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("list_tts_voices (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/models/tts/voices")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.aiModels.listTtsVoices();
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("list_tts_voices (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/models/tts/voices")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.aiModels.listTtsVoices();
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("list_tts_voices (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/models/tts/voices")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.aiModels.listTtsVoices();
        }).rejects.toThrow(Talkif.InternalServerError);
    });
});
