// This file was auto-generated by Fern from our API Definition.

import * as Talkif from "../../src/api/index";
import { TalkifClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("CallsClient", () => {
    test("list_calls (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            calls: [
                {
                    accountId: "550e8400-e29b-41d4-a716-446655440000",
                    agentConnectedAt: "2024-01-15T09:30:00Z",
                    agentDisconnectedAt: "2024-01-15T09:30:00Z",
                    agentStatus: "pending",
                    botSpeechSecs: 78.2,
                    callSid: "CA1234567890abcdef1234567890abcdef",
                    campaignId: "campaignId",
                    completionTokens: 512,
                    contact: {
                        company: "Acme Corp",
                        id: "550e8400-e29b-41d4-a716-446655440000",
                        name: "Jane Smith",
                        tags: ["vip", "priority"],
                    },
                    cost: "0.053200",
                    createdAt: "2026-01-15T10:30:00Z",
                    dataRetainedAt: "2024-01-15T09:30:00Z",
                    direction: "inbound",
                    duration: 125,
                    endReason: "caller_hangup",
                    endedAt: "2024-01-15T09:30:00Z",
                    failureCode: "capacity_limit",
                    failureReason: "Recipient did not answer",
                    firstSpeechMs: 1250,
                    flowId: "flowId",
                    fromNumber: "+15559876543",
                    functionCallCount: 3,
                    functionCallTotalMs: 1730,
                    id: "550e8400-e29b-41d4-a716-446655440000",
                    interruptedTurns: 2,
                    isAnalyzed: true,
                    isLead: true,
                    isRecorded: true,
                    promptTokens: 2048,
                    providerType: "twilio",
                    queueInfo: {
                        attemptCount: 0,
                        estimatedWaitSeconds: 30,
                        position: 3,
                        queueId: "550e8400-e29b-41d4-a716-446655440000",
                        queuedAt: "2026-01-15T10:30:00Z",
                        status: "pending",
                    },
                    recordingDurationSecs: 120.5,
                    recordingExpiresAt: "2024-01-15T09:30:00Z",
                    recordingFileSizeBytes: 1048576,
                    recordingStatus: "ready",
                    recordingStorageCost: "0.000150",
                    scheduleId: "scheduleId",
                    source: "direct",
                    startedAt: "2024-01-15T09:30:00Z",
                    status: "queued",
                    telephonyStatus: "initiating",
                    toNumber: "+15551234567",
                    triggerDetail: "Spring promo form",
                    ttsCharacters: 3200,
                    turnCount: 12,
                    userSpeechSecs: 45.5,
                    voicemailDetectedAt: "2024-01-15T09:30:00Z",
                    voicemailStatus: "voicemail_detected",
                },
            ],
            meta: { limit: 20, offset: 0, total: 142 },
        };

        server.mockEndpoint().get("/api/v1/calls").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.calls.listCalls();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_calls (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server.mockEndpoint().get("/api/v1/calls").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.calls.listCalls();
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("list_calls (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server.mockEndpoint().get("/api/v1/calls").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.calls.listCalls();
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("list_calls (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server.mockEndpoint().get("/api/v1/calls").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.calls.listCalls();
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("list_calls (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server.mockEndpoint().get("/api/v1/calls").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.calls.listCalls();
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("make_call (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            flowId: "550e8400-e29b-41d4-a716-446655440000",
            fromNumber: "+15559876543",
            providerId: "550e8400-e29b-41d4-a716-446655440000",
            toNumber: "+15551234567",
        };
        const rawResponseBody = {
            type: "initiated",
            callId: "550e8400-e29b-41d4-a716-446655440000",
            callSid: "CA1234567890abcdef1234567890abcdef",
            flowId: "flowId",
            fromNumber: "+15559876543",
            providerId: "providerId",
            providerType: "twilio",
            status: "queued",
            toNumber: "+15551234567",
        };

        server
            .mockEndpoint()
            .post("/api/v1/calls")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.calls.makeCall({
            flowId: "550e8400-e29b-41d4-a716-446655440000",
            fromNumber: "+15559876543",
            providerId: "550e8400-e29b-41d4-a716-446655440000",
            toNumber: "+15551234567",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("make_call (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            flowId: "flowId",
            fromNumber: "fromNumber",
            providerId: "providerId",
            toNumber: "toNumber",
        };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/calls")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.makeCall({
                flowId: "flowId",
                fromNumber: "fromNumber",
                providerId: "providerId",
                toNumber: "toNumber",
            });
        }).rejects.toThrow(Talkif.BadRequestError);
    });

    test("make_call (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            flowId: "flowId",
            fromNumber: "fromNumber",
            providerId: "providerId",
            toNumber: "toNumber",
        };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/calls")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.makeCall({
                flowId: "flowId",
                fromNumber: "fromNumber",
                providerId: "providerId",
                toNumber: "toNumber",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("make_call (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            flowId: "flowId",
            fromNumber: "fromNumber",
            providerId: "providerId",
            toNumber: "toNumber",
        };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/calls")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.makeCall({
                flowId: "flowId",
                fromNumber: "fromNumber",
                providerId: "providerId",
                toNumber: "toNumber",
            });
        }).rejects.toThrow(Talkif.PaymentRequiredError);
    });

    test("make_call (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            flowId: "flowId",
            fromNumber: "fromNumber",
            providerId: "providerId",
            toNumber: "toNumber",
        };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/calls")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.makeCall({
                flowId: "flowId",
                fromNumber: "fromNumber",
                providerId: "providerId",
                toNumber: "toNumber",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("make_call (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            flowId: "flowId",
            fromNumber: "fromNumber",
            providerId: "providerId",
            toNumber: "toNumber",
        };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/calls")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.makeCall({
                flowId: "flowId",
                fromNumber: "fromNumber",
                providerId: "providerId",
                toNumber: "toNumber",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("make_call (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            flowId: "flowId",
            fromNumber: "fromNumber",
            providerId: "providerId",
            toNumber: "toNumber",
        };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/calls")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.makeCall({
                flowId: "flowId",
                fromNumber: "fromNumber",
                providerId: "providerId",
                toNumber: "toNumber",
            });
        }).rejects.toThrow(Talkif.UnprocessableEntityError);
    });

    test("make_call (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            flowId: "flowId",
            fromNumber: "fromNumber",
            providerId: "providerId",
            toNumber: "toNumber",
        };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/calls")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.makeCall({
                flowId: "flowId",
                fromNumber: "fromNumber",
                providerId: "providerId",
                toNumber: "toNumber",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("make_call (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            flowId: "flowId",
            fromNumber: "fromNumber",
            providerId: "providerId",
            toNumber: "toNumber",
        };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/calls")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.makeCall({
                flowId: "flowId",
                fromNumber: "fromNumber",
                providerId: "providerId",
                toNumber: "toNumber",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("get_call_details (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            accountId: "550e8400-e29b-41d4-a716-446655440000",
            agentConnectedAt: "2024-01-15T09:30:00Z",
            agentDisconnectedAt: "2024-01-15T09:30:00Z",
            agentStatus: "pending",
            botSpeechSecs: 78.2,
            callSid: "CA1234567890abcdef1234567890abcdef",
            campaignId: "campaignId",
            completionTokens: 512,
            contact: {
                company: "Acme Corp",
                id: "550e8400-e29b-41d4-a716-446655440000",
                name: "Jane Smith",
                tags: ["vip", "priority"],
            },
            cost: "0.053200",
            createdAt: "2026-01-15T10:30:00Z",
            dataRetainedAt: "2024-01-15T09:30:00Z",
            direction: "inbound",
            duration: 125,
            endReason: "caller_hangup",
            endedAt: "2024-01-15T09:30:00Z",
            failureCode: "capacity_limit",
            failureReason: "Recipient did not answer",
            firstSpeechMs: 1250,
            flowId: "flowId",
            fromNumber: "+15559876543",
            functionCallCount: 3,
            functionCallTotalMs: 1730,
            id: "550e8400-e29b-41d4-a716-446655440000",
            interruptedTurns: 2,
            isAnalyzed: true,
            isLead: true,
            isRecorded: true,
            promptTokens: 2048,
            providerType: "twilio",
            queueInfo: {
                attemptCount: 0,
                estimatedWaitSeconds: 30,
                position: 3,
                queueId: "550e8400-e29b-41d4-a716-446655440000",
                queuedAt: "2026-01-15T10:30:00Z",
                status: "pending",
            },
            recordingDurationSecs: 120.5,
            recordingExpiresAt: "2024-01-15T09:30:00Z",
            recordingFileSizeBytes: 1048576,
            recordingStatus: "ready",
            recordingStorageCost: "0.000150",
            scheduleId: "scheduleId",
            source: "direct",
            startedAt: "2024-01-15T09:30:00Z",
            status: "queued",
            telephonyStatus: "initiating",
            toNumber: "+15551234567",
            triggerDetail: "Spring promo form",
            ttsCharacters: 3200,
            turnCount: 12,
            userSpeechSecs: 45.5,
            voicemailDetectedAt: "2024-01-15T09:30:00Z",
            voicemailStatus: "voicemail_detected",
        };

        server
            .mockEndpoint()
            .get("/api/v1/calls/callId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.calls.getCallDetails({
            callId: "callId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_call_details (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/calls/callId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.getCallDetails({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("get_call_details (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/calls/callId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.getCallDetails({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("get_call_details (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/calls/callId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.getCallDetails({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("get_call_details (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/calls/callId")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.getCallDetails({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("get_call_details (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/calls/callId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.getCallDetails({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("analyze_call (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            actionItems: [{ completed: true, description: "Send follow-up email with pricing information" }],
            callerInfo: { company: "Acme Corp", email: "john@acme.com", name: "John Smith", role: "VP of Sales" },
            intents: [{ confidence: "high", name: "schedule_appointment" }],
            outcome: {
                confidence: 0.92,
                nextStep: "Send appointment confirmation email",
                outcomeType: "appointment_set",
            },
            sentiment: { overall: "positive", score: 0.85 },
            summary: "Customer called to reschedule their dental appointment from Tuesday to Thursday.",
            topics: ["appointment", "pricing", "availability"],
        };

        server
            .mockEndpoint()
            .post("/api/v1/calls/callId/analyze")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.calls.analyzeCall({
            callId: "callId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("analyze_call (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/calls/callId/analyze")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.analyzeCall({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.BadRequestError);
    });

    test("analyze_call (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/calls/callId/analyze")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.analyzeCall({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("analyze_call (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/calls/callId/analyze")
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.analyzeCall({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.PaymentRequiredError);
    });

    test("analyze_call (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/calls/callId/analyze")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.analyzeCall({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("analyze_call (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/calls/callId/analyze")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.analyzeCall({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("analyze_call (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/calls/callId/analyze")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.analyzeCall({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("analyze_call (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/calls/callId/analyze")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.analyzeCall({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("analyze_call (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/calls/callId/analyze")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.analyzeCall({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.ServiceUnavailableError);
    });

    test("get_call_recording (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            durationSecs: 120.5,
            expiresInSecs: 3600,
            fileSizeBytes: 1048576,
            recordingExpiresAt: "2026-04-15T10:30:00Z",
            url: "https://s3.amazonaws.com/bucket/recording.wav?X-Amz-Signature=abc123",
        };

        server
            .mockEndpoint()
            .get("/api/v1/calls/callId/recording")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.calls.getCallRecording({
            callId: "callId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_call_recording (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/calls/callId/recording")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.getCallRecording({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.BadRequestError);
    });

    test("get_call_recording (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/calls/callId/recording")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.getCallRecording({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("get_call_recording (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/calls/callId/recording")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.getCallRecording({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("get_call_recording (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/calls/callId/recording")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.getCallRecording({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("get_call_recording (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/calls/callId/recording")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.getCallRecording({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("get_call_recording (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/calls/callId/recording")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.getCallRecording({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("get_call_recording (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/calls/callId/recording")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.getCallRecording({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.ServiceUnavailableError);
    });

    test("delete_call_recording (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/api/v1/calls/callId/recording").respondWith().statusCode(200).build();

        const response = await client.calls.deleteCallRecording({
            callId: "callId",
        });
        expect(response).toEqual(undefined);
    });

    test("delete_call_recording (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/calls/callId/recording")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.deleteCallRecording({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.BadRequestError);
    });

    test("delete_call_recording (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/calls/callId/recording")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.deleteCallRecording({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("delete_call_recording (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/calls/callId/recording")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.deleteCallRecording({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("delete_call_recording (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/calls/callId/recording")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.deleteCallRecording({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("delete_call_recording (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/calls/callId/recording")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.deleteCallRecording({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("delete_call_recording (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/calls/callId/recording")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.deleteCallRecording({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("delete_call_recording (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/calls/callId/recording")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.deleteCallRecording({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.ServiceUnavailableError);
    });

    test("get_call_transcript (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            callId: "550e8400-e29b-41d4-a716-446655440000",
            duration: 125,
            endedAt: "2024-01-15T09:30:00Z",
            messages: [
                {
                    content: "Hello, how can I help you today?",
                    durationMs: 2500,
                    llmModel: "openai/gpt-4.1",
                    metrics: {
                        llmCompletionTokens: 128,
                        llmLatencyMs: 1200,
                        llmPromptTokens: 512,
                        llmThinkingMs: 460,
                        llmTtfatMs: 780,
                        llmTtfbMs: 320,
                        sttProcessingMs: 250,
                        sttTtfbMs: 85,
                        textAggregationMs: 95,
                        ttsCharacters: 245,
                        ttsProcessingMs: 800,
                        ttsTtfbMs: 150,
                    },
                    speaker: "ai",
                    speakerName: "Appointment Bot",
                    timestampMs: 1500,
                    ttsModel: "elevenlabs/eleven_turbo_v2_5",
                    turnNumber: 1,
                },
            ],
            startedAt: "2026-01-15T10:30:00Z",
            transcript: "AI: Hello, how can I help you today?\nHuman: I'd like to schedule an appointment.",
        };

        server
            .mockEndpoint()
            .get("/api/v1/calls/callId/transcript")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.calls.getCallTranscript({
            callId: "callId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_call_transcript (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/calls/callId/transcript")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.getCallTranscript({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("get_call_transcript (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/calls/callId/transcript")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.getCallTranscript({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("get_call_transcript (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/calls/callId/transcript")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.getCallTranscript({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("get_call_transcript (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/calls/callId/transcript")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.getCallTranscript({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("get_call_transcript (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/calls/callId/transcript")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.getCallTranscript({
                callId: "callId",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });
});
