// This file was auto-generated by Fern from our API Definition.

import * as Talkif from "../../src/api/index";
import { TalkifClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("PhoneNumbersClient", () => {
    test("list_phone_numbers (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            meta: { limit: 20, offset: 0, total: 142 },
            phoneNumbers: [
                {
                    accountId: "550e8400-e29b-41d4-a716-446655440000",
                    billingStatus: "active",
                    canInitiateCalls: true,
                    capabilities: ["SMS"],
                    channelType: "pstn",
                    connectedAt: "2024-01-15T09:30:00Z",
                    connectedFlow: { id: "550e8400-e29b-41d4-a716-446655440000", name: "Appointment Reminder" },
                    createdAt: "2026-01-15T10:30:00Z",
                    friendlyName: "friendlyName",
                    id: "550e8400-e29b-41d4-a716-446655440000",
                    isVerified: true,
                    monthlyCost: "1.00",
                    nextBillingDate: "2024-01-15T09:30:00Z",
                    phoneNumber: "+15551234567",
                    providerId: "550e8400-e29b-41d4-a716-446655440000",
                    providerPhoneId: "PN1234567890abcdef1234567890abcdef",
                    purchasedAt: "2026-01-15T10:30:00Z",
                    recordingOverride: "do-not-record",
                    releasedAt: "2024-01-15T09:30:00Z",
                    status: "ACTIVE",
                    twilioEdge: "ashburn",
                    twilioRegion: "us1",
                    updatedAt: "2026-01-15T10:30:00Z",
                    verifiedAt: "2024-01-15T09:30:00Z",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.phoneNumbers.listPhoneNumbers();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_phone_numbers (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.listPhoneNumbers();
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("list_phone_numbers (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.listPhoneNumbers();
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("list_phone_numbers (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.listPhoneNumbers();
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("list_phone_numbers (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.listPhoneNumbers();
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("list_available_numbers (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            numbers: [
                {
                    addressRequirements: "none",
                    beta: false,
                    capabilities: ["SMS"],
                    friendlyName: "(555) 123-4567",
                    isoCountry: "US",
                    lata: "lata",
                    latitude: 1.1,
                    locality: "locality",
                    longitude: 1.1,
                    phoneNumber: "+15551234567",
                    postalCode: "postalCode",
                    rateCenter: "rateCenter",
                    region: "region",
                },
            ],
            query: { areaCode: "areaCode", contains: "contains", countryCode: "US" },
        };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers/twilio/available")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.phoneNumbers.listAvailableNumbers({
            providerId: "providerId",
            countryCode: "countryCode",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list_available_numbers (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers/twilio/available")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.listAvailableNumbers({
                providerId: "providerId",
                countryCode: "countryCode",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("list_available_numbers (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers/twilio/available")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.listAvailableNumbers({
                providerId: "providerId",
                countryCode: "countryCode",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("list_available_numbers (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers/twilio/available")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.listAvailableNumbers({
                providerId: "providerId",
                countryCode: "countryCode",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("list_available_numbers (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers/twilio/available")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.listAvailableNumbers({
                providerId: "providerId",
                countryCode: "countryCode",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("list_available_countries (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers/twilio/available-countries")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.phoneNumbers.listAvailableCountries({
            providerId: "providerId",
        });
        expect(response).toEqual(undefined);
    });

    test("list_available_countries (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers/twilio/available-countries")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.listAvailableCountries({
                providerId: "providerId",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("list_available_countries (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers/twilio/available-countries")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.listAvailableCountries({
                providerId: "providerId",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("list_available_countries (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers/twilio/available-countries")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.listAvailableCountries({
                providerId: "providerId",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("list_available_countries (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers/twilio/available-countries")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.listAvailableCountries({
                providerId: "providerId",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("get_pricing (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            countryCode: "US",
            countryName: "United States",
            pricePerMonth: "1.00",
            priceUnit: "USD",
        };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers/twilio/pricing")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.phoneNumbers.getPricing({
            providerId: "providerId",
            countryCode: "countryCode",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_pricing (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers/twilio/pricing")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.getPricing({
                providerId: "providerId",
                countryCode: "countryCode",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("get_pricing (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers/twilio/pricing")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.getPricing({
                providerId: "providerId",
                countryCode: "countryCode",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("get_pricing (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers/twilio/pricing")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.getPricing({
                providerId: "providerId",
                countryCode: "countryCode",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("get_pricing (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers/twilio/pricing")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.getPricing({
                providerId: "providerId",
                countryCode: "countryCode",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("purchase_phone_number (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { phoneNumber: "+15551234567", providerId: "550e8400-e29b-41d4-a716-446655440000" };
        const rawResponseBody = {
            accountId: "550e8400-e29b-41d4-a716-446655440000",
            billingStatus: "active",
            canInitiateCalls: true,
            capabilities: ["SMS"],
            channelType: "pstn",
            connectedAt: "2024-01-15T09:30:00Z",
            connectedFlow: {
                description: "description",
                id: "550e8400-e29b-41d4-a716-446655440000",
                name: "Appointment Reminder",
                publishedAt: "2024-01-15T09:30:00Z",
            },
            createdAt: "2026-01-15T10:30:00Z",
            friendlyName: "friendlyName",
            id: "550e8400-e29b-41d4-a716-446655440000",
            isVerified: true,
            monthlyCost: "1.00",
            nextBillingDate: "2024-01-15T09:30:00Z",
            phoneNumber: "+15551234567",
            providerId: "550e8400-e29b-41d4-a716-446655440000",
            providerPhoneId: "PN1234567890abcdef1234567890abcdef",
            purchasedAt: "2026-01-15T10:30:00Z",
            recordingOverride: "do-not-record",
            releasedAt: "2024-01-15T09:30:00Z",
            status: "ACTIVE",
            twilioEdge: "ashburn",
            twilioRegion: "us1",
            updatedAt: "2026-01-15T10:30:00Z",
            verifiedAt: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/api/v1/phone/numbers/twilio/purchase")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.phoneNumbers.purchasePhoneNumber({
            phoneNumber: "+15551234567",
            providerId: "550e8400-e29b-41d4-a716-446655440000",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("purchase_phone_number (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { phoneNumber: "phoneNumber", providerId: "providerId" };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/phone/numbers/twilio/purchase")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.purchasePhoneNumber({
                phoneNumber: "phoneNumber",
                providerId: "providerId",
            });
        }).rejects.toThrow(Talkif.BadRequestError);
    });

    test("purchase_phone_number (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { phoneNumber: "phoneNumber", providerId: "providerId" };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/phone/numbers/twilio/purchase")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.purchasePhoneNumber({
                phoneNumber: "phoneNumber",
                providerId: "providerId",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("purchase_phone_number (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { phoneNumber: "phoneNumber", providerId: "providerId" };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/phone/numbers/twilio/purchase")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.purchasePhoneNumber({
                phoneNumber: "phoneNumber",
                providerId: "providerId",
            });
        }).rejects.toThrow(Talkif.PaymentRequiredError);
    });

    test("purchase_phone_number (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { phoneNumber: "phoneNumber", providerId: "providerId" };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/phone/numbers/twilio/purchase")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.purchasePhoneNumber({
                phoneNumber: "phoneNumber",
                providerId: "providerId",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("purchase_phone_number (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { phoneNumber: "phoneNumber", providerId: "providerId" };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/phone/numbers/twilio/purchase")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.purchasePhoneNumber({
                phoneNumber: "phoneNumber",
                providerId: "providerId",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("purchase_phone_number (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { phoneNumber: "phoneNumber", providerId: "providerId" };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/phone/numbers/twilio/purchase")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.purchasePhoneNumber({
                phoneNumber: "phoneNumber",
                providerId: "providerId",
            });
        }).rejects.toThrow(Talkif.ConflictError);
    });

    test("purchase_phone_number (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { phoneNumber: "phoneNumber", providerId: "providerId" };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/phone/numbers/twilio/purchase")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.purchasePhoneNumber({
                phoneNumber: "phoneNumber",
                providerId: "providerId",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("purchase_phone_number (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { phoneNumber: "phoneNumber", providerId: "providerId" };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .post("/api/v1/phone/numbers/twilio/purchase")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.purchasePhoneNumber({
                phoneNumber: "phoneNumber",
                providerId: "providerId",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("get_phone_number (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            accountId: "550e8400-e29b-41d4-a716-446655440000",
            billingStatus: "active",
            canInitiateCalls: true,
            capabilities: ["SMS"],
            channelType: "pstn",
            connectedAt: "2024-01-15T09:30:00Z",
            connectedFlow: {
                description: "description",
                id: "550e8400-e29b-41d4-a716-446655440000",
                name: "Appointment Reminder",
                publishedAt: "2024-01-15T09:30:00Z",
            },
            createdAt: "2026-01-15T10:30:00Z",
            friendlyName: "friendlyName",
            id: "550e8400-e29b-41d4-a716-446655440000",
            isVerified: true,
            monthlyCost: "1.00",
            nextBillingDate: "2024-01-15T09:30:00Z",
            phoneNumber: "+15551234567",
            providerId: "550e8400-e29b-41d4-a716-446655440000",
            providerPhoneId: "PN1234567890abcdef1234567890abcdef",
            purchasedAt: "2026-01-15T10:30:00Z",
            recordingOverride: "do-not-record",
            releasedAt: "2024-01-15T09:30:00Z",
            status: "ACTIVE",
            twilioEdge: "ashburn",
            twilioRegion: "us1",
            updatedAt: "2026-01-15T10:30:00Z",
            verifiedAt: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.phoneNumbers.getPhoneNumber({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_phone_number (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers/id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.getPhoneNumber({
                id: "id",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("get_phone_number (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers/id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.getPhoneNumber({
                id: "id",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("get_phone_number (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.getPhoneNumber({
                id: "id",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("get_phone_number (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers/id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.getPhoneNumber({
                id: "id",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("get_phone_number (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .get("/api/v1/phone/numbers/id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.getPhoneNumber({
                id: "id",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("update_phone_number (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            accountId: "550e8400-e29b-41d4-a716-446655440000",
            billingStatus: "active",
            canInitiateCalls: true,
            capabilities: ["SMS"],
            channelType: "pstn",
            connectedAt: "2024-01-15T09:30:00Z",
            connectedFlow: {
                description: "description",
                id: "550e8400-e29b-41d4-a716-446655440000",
                name: "Appointment Reminder",
                publishedAt: "2024-01-15T09:30:00Z",
            },
            createdAt: "2026-01-15T10:30:00Z",
            friendlyName: "friendlyName",
            id: "550e8400-e29b-41d4-a716-446655440000",
            isVerified: true,
            monthlyCost: "1.00",
            nextBillingDate: "2024-01-15T09:30:00Z",
            phoneNumber: "+15551234567",
            providerId: "550e8400-e29b-41d4-a716-446655440000",
            providerPhoneId: "PN1234567890abcdef1234567890abcdef",
            purchasedAt: "2026-01-15T10:30:00Z",
            recordingOverride: "do-not-record",
            releasedAt: "2024-01-15T09:30:00Z",
            status: "ACTIVE",
            twilioEdge: "ashburn",
            twilioRegion: "us1",
            updatedAt: "2026-01-15T10:30:00Z",
            verifiedAt: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .put("/api/v1/phone/numbers/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.phoneNumbers.updatePhoneNumber({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update_phone_number (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .put("/api/v1/phone/numbers/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.updatePhoneNumber({
                id: "id",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("update_phone_number (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .put("/api/v1/phone/numbers/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.updatePhoneNumber({
                id: "id",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("update_phone_number (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .put("/api/v1/phone/numbers/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.updatePhoneNumber({
                id: "id",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("update_phone_number (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .put("/api/v1/phone/numbers/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.updatePhoneNumber({
                id: "id",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("update_phone_number (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .put("/api/v1/phone/numbers/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.updatePhoneNumber({
                id: "id",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("release_phone_number (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/api/v1/phone/numbers/id").respondWith().statusCode(200).build();

        const response = await client.phoneNumbers.releasePhoneNumber({
            id: "id",
        });
        expect(response).toEqual(undefined);
    });

    test("release_phone_number (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/phone/numbers/id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.releasePhoneNumber({
                id: "id",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("release_phone_number (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/phone/numbers/id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.releasePhoneNumber({
                id: "id",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("release_phone_number (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/phone/numbers/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.releasePhoneNumber({
                id: "id",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("release_phone_number (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/phone/numbers/id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.releasePhoneNumber({
                id: "id",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("release_phone_number (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .delete("/api/v1/phone/numbers/id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.releasePhoneNumber({
                id: "id",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("connect_flow (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { flowId: "550e8400-e29b-41d4-a716-446655440000" };
        const rawResponseBody = {
            accountId: "550e8400-e29b-41d4-a716-446655440000",
            billingStatus: "active",
            canInitiateCalls: true,
            capabilities: ["SMS"],
            channelType: "pstn",
            connectedAt: "2024-01-15T09:30:00Z",
            connectedFlow: {
                description: "description",
                id: "550e8400-e29b-41d4-a716-446655440000",
                name: "Appointment Reminder",
                publishedAt: "2024-01-15T09:30:00Z",
            },
            createdAt: "2026-01-15T10:30:00Z",
            friendlyName: "friendlyName",
            id: "550e8400-e29b-41d4-a716-446655440000",
            isVerified: true,
            monthlyCost: "1.00",
            nextBillingDate: "2024-01-15T09:30:00Z",
            phoneNumber: "+15551234567",
            providerId: "550e8400-e29b-41d4-a716-446655440000",
            providerPhoneId: "PN1234567890abcdef1234567890abcdef",
            purchasedAt: "2026-01-15T10:30:00Z",
            recordingOverride: "do-not-record",
            releasedAt: "2024-01-15T09:30:00Z",
            status: "ACTIVE",
            twilioEdge: "ashburn",
            twilioRegion: "us1",
            updatedAt: "2026-01-15T10:30:00Z",
            verifiedAt: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .patch("/api/v1/phone/numbers/phoneNumberId/connect-flow")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.phoneNumbers.connectFlow({
            phoneNumberId: "phoneNumberId",
            flowId: "550e8400-e29b-41d4-a716-446655440000",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("connect_flow (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { flowId: "flowId" };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .patch("/api/v1/phone/numbers/phoneNumberId/connect-flow")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.connectFlow({
                phoneNumberId: "phoneNumberId",
                flowId: "flowId",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("connect_flow (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { flowId: "flowId" };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .patch("/api/v1/phone/numbers/phoneNumberId/connect-flow")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.connectFlow({
                phoneNumberId: "phoneNumberId",
                flowId: "flowId",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("connect_flow (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { flowId: "flowId" };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .patch("/api/v1/phone/numbers/phoneNumberId/connect-flow")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.connectFlow({
                phoneNumberId: "phoneNumberId",
                flowId: "flowId",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("connect_flow (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { flowId: "flowId" };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .patch("/api/v1/phone/numbers/phoneNumberId/connect-flow")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.connectFlow({
                phoneNumberId: "phoneNumberId",
                flowId: "flowId",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("connect_flow (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { flowId: "flowId" };
        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .patch("/api/v1/phone/numbers/phoneNumberId/connect-flow")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.connectFlow({
                phoneNumberId: "phoneNumberId",
                flowId: "flowId",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });

    test("disconnect_flow (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            accountId: "550e8400-e29b-41d4-a716-446655440000",
            billingStatus: "active",
            canInitiateCalls: true,
            capabilities: ["SMS"],
            channelType: "pstn",
            connectedAt: "2024-01-15T09:30:00Z",
            connectedFlow: {
                description: "description",
                id: "550e8400-e29b-41d4-a716-446655440000",
                name: "Appointment Reminder",
                publishedAt: "2024-01-15T09:30:00Z",
            },
            createdAt: "2026-01-15T10:30:00Z",
            friendlyName: "friendlyName",
            id: "550e8400-e29b-41d4-a716-446655440000",
            isVerified: true,
            monthlyCost: "1.00",
            nextBillingDate: "2024-01-15T09:30:00Z",
            phoneNumber: "+15551234567",
            providerId: "550e8400-e29b-41d4-a716-446655440000",
            providerPhoneId: "PN1234567890abcdef1234567890abcdef",
            purchasedAt: "2026-01-15T10:30:00Z",
            recordingOverride: "do-not-record",
            releasedAt: "2024-01-15T09:30:00Z",
            status: "ACTIVE",
            twilioEdge: "ashburn",
            twilioRegion: "us1",
            updatedAt: "2026-01-15T10:30:00Z",
            verifiedAt: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .patch("/api/v1/phone/numbers/phoneNumberId/disconnect-flow")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.phoneNumbers.disconnectFlow({
            phoneNumberId: "phoneNumberId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("disconnect_flow (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .patch("/api/v1/phone/numbers/phoneNumberId/disconnect-flow")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.disconnectFlow({
                phoneNumberId: "phoneNumberId",
            });
        }).rejects.toThrow(Talkif.UnauthorizedError);
    });

    test("disconnect_flow (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .patch("/api/v1/phone/numbers/phoneNumberId/disconnect-flow")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.disconnectFlow({
                phoneNumberId: "phoneNumberId",
            });
        }).rejects.toThrow(Talkif.ForbiddenError);
    });

    test("disconnect_flow (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .patch("/api/v1/phone/numbers/phoneNumberId/disconnect-flow")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.disconnectFlow({
                phoneNumberId: "phoneNumberId",
            });
        }).rejects.toThrow(Talkif.NotFoundError);
    });

    test("disconnect_flow (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .patch("/api/v1/phone/numbers/phoneNumberId/disconnect-flow")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.disconnectFlow({
                phoneNumberId: "phoneNumberId",
            });
        }).rejects.toThrow(Talkif.TooManyRequestsError);
    });

    test("disconnect_flow (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TalkifClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { code: "invalid_credentials", detail: "detail", status: 1, title: "title" };

        server
            .mockEndpoint()
            .patch("/api/v1/phone/numbers/phoneNumberId/disconnect-flow")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.phoneNumbers.disconnectFlow({
                phoneNumberId: "phoneNumberId",
            });
        }).rejects.toThrow(Talkif.InternalServerError);
    });
});
