// This file was auto-generated by Fern from our API Definition.

import { AccountsClient } from "./api/resources/accounts/client/Client.js";
import { AiModelsClient } from "./api/resources/aiModels/client/Client.js";
import { AnalyticsClient } from "./api/resources/analytics/client/Client.js";
import { BillingClient } from "./api/resources/billing/client/Client.js";
import { CallsClient } from "./api/resources/calls/client/Client.js";
import { CampaignsClient } from "./api/resources/campaigns/client/Client.js";
import { ContactsClient } from "./api/resources/contacts/client/Client.js";
import { DoNotCallClient } from "./api/resources/doNotCall/client/Client.js";
import { ErrorsClient } from "./api/resources/errors/client/Client.js";
import { FlowFunctionsClient } from "./api/resources/flowFunctions/client/Client.js";
import { FlowsClient } from "./api/resources/flows/client/Client.js";
import { FlowTemplatesClient } from "./api/resources/flowTemplates/client/Client.js";
import { PhoneNumbersClient } from "./api/resources/phoneNumbers/client/Client.js";
import { PhoneProvidersClient } from "./api/resources/phoneProviders/client/Client.js";
import { PublicCallsClient } from "./api/resources/publicCalls/client/Client.js";
import { SchedulesClient } from "./api/resources/schedules/client/Client.js";
import { TransfersClient } from "./api/resources/transfers/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace TalkifClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class TalkifClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<TalkifClient.Options>;
    protected _billing: BillingClient | undefined;
    protected _calls: CallsClient | undefined;
    protected _campaigns: CampaignsClient | undefined;
    protected _analytics: AnalyticsClient | undefined;
    protected _contacts: ContactsClient | undefined;
    protected _doNotCall: DoNotCallClient | undefined;
    protected _errors: ErrorsClient | undefined;
    protected _flowFunctions: FlowFunctionsClient | undefined;
    protected _flowTemplates: FlowTemplatesClient | undefined;
    protected _flows: FlowsClient | undefined;
    protected _aiModels: AiModelsClient | undefined;
    protected _accounts: AccountsClient | undefined;
    protected _phoneNumbers: PhoneNumbersClient | undefined;
    protected _phoneProviders: PhoneProvidersClient | undefined;
    protected _publicCalls: PublicCallsClient | undefined;
    protected _schedules: SchedulesClient | undefined;
    protected _transfers: TransfersClient | undefined;

    constructor(options: TalkifClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get billing(): BillingClient {
        return (this._billing ??= new BillingClient(this._options));
    }

    public get calls(): CallsClient {
        return (this._calls ??= new CallsClient(this._options));
    }

    public get campaigns(): CampaignsClient {
        return (this._campaigns ??= new CampaignsClient(this._options));
    }

    public get analytics(): AnalyticsClient {
        return (this._analytics ??= new AnalyticsClient(this._options));
    }

    public get contacts(): ContactsClient {
        return (this._contacts ??= new ContactsClient(this._options));
    }

    public get doNotCall(): DoNotCallClient {
        return (this._doNotCall ??= new DoNotCallClient(this._options));
    }

    public get errors(): ErrorsClient {
        return (this._errors ??= new ErrorsClient(this._options));
    }

    public get flowFunctions(): FlowFunctionsClient {
        return (this._flowFunctions ??= new FlowFunctionsClient(this._options));
    }

    public get flowTemplates(): FlowTemplatesClient {
        return (this._flowTemplates ??= new FlowTemplatesClient(this._options));
    }

    public get flows(): FlowsClient {
        return (this._flows ??= new FlowsClient(this._options));
    }

    public get aiModels(): AiModelsClient {
        return (this._aiModels ??= new AiModelsClient(this._options));
    }

    public get accounts(): AccountsClient {
        return (this._accounts ??= new AccountsClient(this._options));
    }

    public get phoneNumbers(): PhoneNumbersClient {
        return (this._phoneNumbers ??= new PhoneNumbersClient(this._options));
    }

    public get phoneProviders(): PhoneProvidersClient {
        return (this._phoneProviders ??= new PhoneProvidersClient(this._options));
    }

    public get publicCalls(): PublicCallsClient {
        return (this._publicCalls ??= new PublicCallsClient(this._options));
    }

    public get schedules(): SchedulesClient {
        return (this._schedules ??= new SchedulesClient(this._options));
    }

    public get transfers(): TransfersClient {
        return (this._transfers ??= new TransfersClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
